# Description: The Linux kernel
# URL: http://www.kernel.org
# License: GPLv2

name=linux-source
version=$KERNEL_VERSION
release=1
source=(http://mirror.mini-distribution.io/raspberrypi/linux-$version-rpi-git46e2d4d1bd.tar.xz)
options=(nostrip)

build()
{
    mkdir -p $PKG/usr/src
    mv linux-$version-rpi-git46e2d4d1bd $PKG/usr/src/linux
}
