# Description: The Linux kernel
# URL: http://www.kernel.org
# License: GPLv2

name=linux-source
version=$KERNEL_VERSION
release=1
source=(https://www.kernel.org/pub/linux/kernel/v4.x/linux-$version.tar.xz
        http://mirror.mini-distribution.io/raspberrypi/linux-4.1.3-rpi-patches.tar.xz)
options=(nostrip)

build()
{
    mkdir -p $PKG/usr/src
    mv linux-$version $PKG/usr/src/linux

    cd $PKG/usr/src/linux

    for file in $SRC/linux-$version-rpi-patches/*
    do
        patch -p1 -i $file
    done
}
