# Description: Bootloader/GPU firmware for the Raspberry Pi
# URL: https://github.com/raspberrypi/firmware
# License: BSD

name=rpi-firmware-boot
version=git464ce4fc
release=1
source=(http://mirror.mini-distribution.io/raspberrypi/$name-$version.tar.xz)
depends=zlib

build() {
    cd $name-$version

    mkdir -p $OUTPUT/boot
    cp bootcode.bin $OUTPUT/boot
    cp start.elf $OUTPUT/boot
}
