# Description: Bootloader/GPU firmware for the Raspberry Pi
# URL: https://github.com/raspberrypi/firmware
# License: BSD

name=rpi-firmware-boot
version=giteb04fcf96b
release=1
source=(http://mirror.mini-distribution.io/raspberrypi/$name-$version.tar.xz
        cmdline.txt config.txt)

build() {
    cd $name-$version

    mkdir -p $OUTPUT/boot
    cp bootcode.bin $OUTPUT/boot
    cp start.elf $OUTPUT/boot
    cp $SRC/config.txt $OUTPUT/boot
    cp $SRC/cmdline.txt $OUTPUT/boot
}
